# define options/settings
APP:
  TITLE: "Mech Warrior"
  SCREEN_WIDTH: 1000
  SCREEN_HEIGHT: 1000

GAME:
  FPS: 60
  GRAVITY: 2
  SURFACE_WIDTH: 800 # SCREEN_WIDTH + (TILE_SIZE * 2)
  SURFACE_HEIGHT: 800 # SCREEN_HEIGHT + (TILE_SIZE * 2)

TILE:
  DIMENSION: 32

SPRITESHEET:
  BASIC: "MechWarrior.png"
  EXPLOSION: "Explosion.png"

PLAYER:
  ACCELERATION: 1
  FRICTION: -0.12

COLORS:
  BLACK:
    - 0
    - 0
    - 0

